spring.application.name=VeterinaryClinic

# database
spring.datasource.url: jdbc:mysql://localhost:3306/veterinaryclinic?serverTimezone=Asia/Seoul&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: 1234
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.example.VeterinaryClinic.DTO

# MyBatis log connect SLF4J
mybatis.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl

# Mapper SQL log debug level
logging.level.com.example.VeterinaryClinic.Mapper=DEBUG

# MyBatis inner log view
logging.level.org.mybatis=DEBUG


# thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

#Webflux
implementation 'org.springframework.boot:spring-boot-starter-webflux'

#login
kakao.client.secret=0ec842b0a2984fa23f7e2ac2315598af
naver.client.id=p5WLYChHNHj3WwvpSM_z
naver.client.secret=9d02C6vLwl
